# Generated by Django 4.1.4 on 2023-01-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('valor_original', models.FloatField(default=0)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='pagamento.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoAntecipacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('NEGADO', 'Negado')], default='Pendente', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, default='')),
                ('novo_valor', models.FloatField(blank=True, default=0)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacaoantecipacao', to='pagamento.pagamento')),
            ],
        ),
    ]
